[tool.black]
line-length = 160

[tool.poetry]
name = "IT2zBot"
version = "0.1.0"
description = ""
authors = ["Eulentier161 <eulentier161@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.0.1"
pyaml = "^21.10.1"
httpx = "^0.23.0"
uvloop = "^0.17.0"
PyJWT = { version = "^2.4.0", extras = ["crypto"] }
beautifulsoup4 = "^4.11.2"
certifi = "^2023.7.22"
aiohttp = "^3.9.0"
cryptography = "^41.0.4"
feedparser = "^6.0.10"
markdownify = "^0.11.6"

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[tool.poetry.scripts]
it2zbot = "it2zbot.bot:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
