[tool.black]
line-length = 160

[tool.poetry]
name = "IT2zBot2"
version = "0.1.0"
description = ""
authors = ["Eulentier161 <eulentier161@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.0.1"
pyaml = "^21.10.1"
httpx = "^0.23.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
ipykernel = "^6.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
